import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/views/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.tsx',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--primary)',
          1: 'var(--primary-1)',
          2: 'var(--primary-2)',
          3: 'var(--primary-3)',
          4: 'var(--primary-4)',
          5: 'var(--primary-5)',
          6: 'var(--primary-6)',
          7: 'var(--primary-7)',
          8: 'var(--primary-8)',
          9: 'var(--primary-9)',
          10: 'var(--primary-10)',
          11: 'var(--primary-11)',
          12: 'var(--primary-12)',
          16: 'var(--primary-16)',
        },
        black: 'var(--black)',
        blackMain: 'var(--black-main)',
        gray: {
          1: 'var(--gray-1)',
          2: 'var(--gray-2)',
          3: 'var(--gray-3)',
          4: 'var(--gray-4)',
          5: 'var(--gray-5)',
          6: 'var(--gray-6)',
          650: '#2A2F3A',
          7: 'var(--gray-7)',
          8: 'var(--gray-8)',
          9: 'var(--gray-9)',
        },
        orange: {
          DEFAULT: 'var(--orange)',
          1: 'var(--orange-1)',
          2: 'var(--orange-2)',
          3: 'var(--orange-3)',
          4: 'var(--orange-4)',
          5: 'var(--orange-5)',
          6: 'var(--orange-6)',
          7: 'var(--orange-7)',
          8: 'var(--orange-8)',
          9: 'var(--orange-9)',
          10: 'var(--orange-10)',
          16: 'var(--orange-16)',
        },
        red: {
          DEFAULT: 'var(--red)',
          1: 'var(--red-1)',
          2: 'var(--red-2)',
          3: 'var(--red-3)',
          4: 'var(--red-4)',
          5: 'var(--red-5)',
          6: 'var(--red-6)',
          7: 'var(--red-7)',
          8: 'var(--red-8)',
          9: 'var(--red-9)',
          10: 'var(--red-10)',
          16: 'var(--red-16)',
        },
        green: {
          DEFAULT: 'var(--green)',
          1: 'var(--green-1)',
          2: 'var(--green-2)',
          3: 'var(--green-3)',
          4: 'var(--green-4)',
          5: 'var(--green-5)',
          6: 'var(--green-6)',
          7: 'var(--green-7)',
          8: 'var(--green-8)',
          9: 'var(--green-9)',
          10: 'var(--green-10)',
          16: 'var(--green-16)',
        },
        yellow: {
          DEFAULT: 'var(--yellow)',
          1: 'var(--yellow-1)',
          2: 'var(--yellow-2)',
          3: 'var(--yellow-3)',
          4: 'var(--yellow-4)',
          5: 'var(--yellow-5)',
          6: 'var(--yellow-6)',
          7: 'var(--yellow-7)',
          8: 'var(--yellow-8)',
          9: 'var(--yellow-9)',
          10: 'var(--yellow-10)',
        },
      },
      fontSize: {
        'title-lg': [
          '1.375rem',
          {
            fontWeight: 700,
          },
        ],
      },
      fontFamily: {
        Vazir: ['Vazir', 'sans-serif'],
      },
    },
  },
};

export default config;
